enqueue:
    transport:
        default: 'amqp'
        amqp:
            dsn: '%env(ENQUEUE_DSN)%'
            lazy: true
            persisted: true
    client:
        redelivered_delay_time: 5
        prefix: ''
        app_name: 'comrade'
