nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_headers: ['content-type']
            max_age: 3600
        '^/process':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_headers: ['content-type']
            max_age: 3600
