gos_web_socket:
    server:
        port: 9502
        host: '0.0.0.0'
        origin_check: false
        router:
            resources:
                - '../config/ws_routing.yml'
    pushers:
        amqp:
            default: true
            host: 'fake'
            port: 0
            login: 'l'
            password: 'p'

services:
    gos_web_socket.amqp.pusher:
        parent: 'gos_web_socket.abstract.pusher'
        class: 'App\Ws\Ratchet\AmqpPusher'
        arguments:
            - '@enqueue.transport.context'
        tags:
            - { name: 'gos_web_socket.pusher', alias: 'amqp' }

    Gos\Bundle\WebSocketBundle\Pusher\PusherInterface:
        alias: 'gos_web_socket.amqp.pusher'

    gos_web_socket.amqp.server_push_handler:
        class: 'App\Ws\Ratchet\AmqpPusherHandler'
        arguments:
            - '@enqueue.transport.context'
            - '@gos_web_socket.router.wamp'
            - '@gos_web_socket.push_message.serializer'
            - '@event_dispatcher'
            - '@?monolog.logger.websocket'
        tags:
            - { name: 'gos_web_socket.push_handler', alias: 'amqp' }

    app_wamp_topic:
        class: 'App\Ws\Ratchet\WampTopic'
        arguments:
            - 'wamp'
        tags:
            - { name: 'gos_web_socket.topic' }
