yadm:
    mongo_uri: '%env(MONGO_DSN)%'
    models:
        job_template:
            class: 'App\Model\JobTemplate'
            storage_class: 'App\Storage\JobTemplateStorage'
            collection: 'job_template'
            database: '%mongo_database%'

        job:
            class: 'App\Model\Job'
            storage_class: 'App\Storage\JobStorage'
            collection: 'job'
            database: '%mongo_database%'
            pessimistic_lock: true

        exclusive_job:
            class: 'App\Model\ExclusiveJob'
            storage_class: 'App\Storage\ExclusiveJobStorage'
            collection: 'exclusive_job'
            database: '%mongo_database%'
            pessimistic_lock: true

        process:
            class: 'App\Model\Process'
            storage_class: 'App\Storage\ProcessStorage'
            collection: 'pvm_process'
            database: '%mongo_database%'

        process_execution:
            class: 'App\Model\Process'
            storage_class: 'App\Storage\ProcessExecutionStorage'
            collection: 'pvm_process_execution'
            database: '%mongo_database%'
