version: '3'

services:
  jm:
    build: { context: 'docker/jm' }
    # image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './shared:/shared'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
      - './shared/swoole.so:/usr/lib/php/20160303/swoole.so'
      - './docker/swoole.ini:/etc/php/7.1/cli/conf.d/20-swoole.ini'
    env_file: 'apps/jm/.env'
    environment:
      - VIRTUAL_HOST=jm.loc
      - NGINX_WEB_ROOT=/jobs_dev/apps/jm/web
      - NGINX_PHP_FALLBACK=/index.php
      - NGINX_PHP_LOCATION=^/index\.php(/|$$)
      - APP_DEV_PERMITTED=1

  jm_worker:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: "php bin/workers.php"
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './shared:/shared'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
      - './shared/swoole.so:/usr/lib/php/20160303/swoole.so'
      - './docker/swoole.ini:/etc/php/7.1/cli/conf.d/20-swoole.ini'
    env_file: 'apps/jm/.env'

  demo:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: "php consume.php"
    working_dir: '/jobs_dev/apps/demo'
    depends_on:
      - 'rabbitmq'
    volumes:
      - './apps/demo:/jobs_dev/apps/demo:cached'
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './shared:/shared'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
    env_file: 'apps/jm/.env'

  rabbitmq:
    image: 'enqueue/rabbitmq:latest'
    restart: 'always'
    environment:
      - VIRTUAL_HOST=rabbitmq.jm.loc
      - VIRTUAL_PORT=15672
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=jm

  mongo:
    image: 'mongo:3'
    restart: 'always'
    ports:
      - "27017:27017"

  front:
    image: 'jwilder/nginx-proxy'
    restart: 'always'
    ports:
      - "80:80"
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
