version: '3'

services:
  jm:
    build: { context: 'docker/jm' }
    # image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './shared:/shared'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
      - './shared/swoole.so:/usr/lib/php/20160303/swoole.so'
      - './docker/swoole.ini:/etc/php/7.1/cli/conf.d/20-swoole.ini'
    env_file: 'apps/jm/.env'
    environment:
      - VIRTUAL_HOST=jm.loc
      - NGINX_WEB_ROOT=/jobs_dev/apps/jm/public
      - NGINX_PHP_FALLBACK=/index.php
      - NGINX_PHP_LOCATION=^/index\.php(/|$$)
      - APP_DEV_PERMITTED=1

  jmw:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: "php bin/daemon.php"
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
      - 'jms'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './shared:/shared'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
      - './shared/swoole.so:/usr/lib/php/20160303/swoole.so'
      - './docker/swoole.ini:/etc/php/7.1/cli/conf.d/20-swoole.ini'
    env_file: 'apps/jm/.env'
    environment:
      - COMRADE_DEFAULT_CONSUMER_NUMBER=5
      - COMRADE_QUARTZ_CONSUMER_NUMBER=5
      - COMRADE_RUN_QUARTZ=1
      - COMRADE_RUN_WAMP=0
      - WAMP_DSN=ws://jms:9090
      - WAMP_REALM=realm1

  jms:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: "php bin/daemon.php"
    working_dir: '/jobs_dev/apps/jm'
    environment:
      - COMRADE_DEFAULT_CONSUMER_NUMBER=0
      - COMRADE_QUARTZ_CONSUMER_NUMBER=0
      - COMRADE_RUN_QUARTZ=0
      - COMRADE_RUN_WAMP=1
      - WAMP_SERVER_HOST=0.0.0.0
      - WAMP_SERVER_PORT=9090
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './shared:/shared'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
      - './shared/swoole.so:/usr/lib/php/20160303/swoole.so'
      - './docker/swoole.ini:/etc/php/7.1/cli/conf.d/20-swoole.ini'
    env_file: 'apps/jm/.env'
    ports:
      - "9090:9090"

  jmd:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: "php bin/demo_daemon.php"
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './shared:/shared'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
      - './shared/swoole.so:/usr/lib/php/20160303/swoole.so'
      - './docker/swoole.ini:/etc/php/7.1/cli/conf.d/20-swoole.ini'
    env_file: 'apps/jm/.env'

  ui:
    build: { context: 'docker/ui' }
    restart: 'always'
    entrypoint: "ng serve --host=0.0.0.0 --port=80 --public-host=ui.jm.loc"
    working_dir: '/ui'
    volumes:
      - './apps/ui:/ui:cached'
    ports:
      - "3000:80"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=ui.jm.loc

  seeds:
    image: 'formapro/comrade-demo-seeds:latest'
    #entrypoint: 'echo "To populate seeds comment out this entrypoint in docker-compose.yml file\n"'
    restart: 'no'
    depends_on:
      - 'mongo'
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=job_manager

  rabbitmq:
    image: 'enqueue/rabbitmq:latest'
    restart: 'always'
    environment:
      - VIRTUAL_HOST=rabbitmq.jm.loc
      - VIRTUAL_PORT=15672
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=jm

  mongo:
    image: 'mongo:3'
    restart: 'always'
    ports:
      - "27017:27017"
    volumes:
      - './shared:/shared'

  front:
    image: 'jwilder/nginx-proxy'
    restart: 'always'
    ports:
      - "80:80"
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
