version: '3'

services:
  jm:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
    env_file: 'apps/jm/.env'
    environment:
      - VIRTUAL_HOST=jm.loc
      - NGINX_WEB_ROOT=/jobs_dev/apps/jm/web
      - NGINX_PHP_FALLBACK=/index.php
      - NGINX_PHP_LOCATION=^/index\.php(/|$$)
      - APP_DEV_PERMITTED=1

  rabbitmq:
    image: 'enqueue/rabbitmq:latest'
    restart: 'on-failure'
    environment:
      - VIRTUAL_HOST=rabbitmq.jm.loc
      - VIRTUAL_PORT=15672
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=boom

  mongo:
    image: 'mongo:3'
    restart: 'on-failure'
    ports:
      - "27017:27017"

  front:
    image: 'jwilder/nginx-proxy'
    ports:
      - "80:80"
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
