version: '3'

services:
  jm:
    build: { context: 'docker/jm' }
    # image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './pkg/php-shared:/jobs_dev/apps/jm/vendor/comrade/shared:cached'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
    env_file: 'apps/jm/.env'
    environment:
      - VIRTUAL_HOST=jm.loc
      - NGINX_WEB_ROOT=/jobs_dev/apps/jm/public
      - NGINX_PHP_FALLBACK=/index.php
      - NGINX_PHP_LOCATION=^/index\.php(/|$$)
      - APP_DEV_PERMITTED=1

  jmq:
    build: { context: 'docker/jm' }
    restart: 'always'
    entrypoint: 'php bin/console quartz:scheduler -vvv'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './pkg/php-shared:/jobs_dev/apps/jm/vendor/comrade/shared:cached'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
    env_file: 'apps/jm/.env'

  jmw:
    build: { context: 'docker/jm' }
    restart: 'always'
    entrypoint: 'php bin/wamp_server.php'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './pkg/php-shared:/jobs_dev/apps/jm/vendor/comrade/shared:cached'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
    env_file: 'apps/jm/.env'
    ports:
      - '9090:9090'

  jmc:
    build: { context: 'docker/jm' }
    restart: 'always'
    entrypoint: 'php bin/console enqueue:consume --setup-broker --skip=quartz_rpc --receive-timeout=10000 --time-limit="+3600 seconds" --memory-limit=100 -vvv'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
      - 'jmw'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './pkg/php-shared:/jobs_dev/apps/jm/vendor/comrade/shared:cached'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
    env_file: 'apps/jm/.env'

  jmqr:
    build: { context: 'docker/jm' }
    restart: 'always'
    entrypoint: 'php bin/console enqueue:consume quartz_rpc --setup-broker --receive-timeout=10000 --time-limit="+3600 seconds" --memory-limit=100 -vvv'
    working_dir: '/jobs_dev/apps/jm'
    depends_on:
      - 'rabbitmq'
      - 'mongo'
    volumes:
      - './apps/jm:/jobs_dev/apps/jm:cached'
      - './pkg/php-shared:/jobs_dev/apps/jm/vendor/comrade/shared:cached'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
    env_file: 'apps/jm/.env'

  jmdq:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: "php queue_demo.php"
    working_dir: '/jobs_dev/apps/demo'
    depends_on:
      - 'rabbitmq'
    volumes:
      - './apps/demo:/jobs_dev/apps/demo:cached'
      - './pkg/php-shared:/jobs_dev/apps/demo/vendor/comrade/shared:cached'
      - './pkg/php-client:/jobs_dev/apps/demo/vendor/comrade/client:cached'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
    env_file: 'apps/jm/.env'

  jmdh:
    image: 'formapro/nginx-php-fpm:latest-all-exts'
    restart: 'always'
    entrypoint: "php -S 0.0.0.0:80 http_demo.php"
    working_dir: '/jobs_dev/apps/demo'
    volumes:
      - './apps/demo:/jobs_dev/apps/demo:cached'
      - './pkg/php-shared:/jobs_dev/apps/demo/vendor/comrade/shared:cached'
      - './pkg/php-client:/jobs_dev/apps/demo/vendor/comrade/client:cached'
      - './shared/amqp.so:/usr/lib/php/20160303/amqp.so'
    expose:
      - '80'
    environment:
      - VIRTUAL_HOST=demo.jm.loc
    env_file: 'apps/jm/.env'

  ui:
    build: { context: 'docker/ui' }
    restart: 'always'
    entrypoint: "ng serve --host=0.0.0.0 --port=80 --public-host=ui.jm.loc"
    working_dir: '/ui'
    volumes:
      - './apps/ui:/ui:cached'
    ports:
      - "3000:80"
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=ui.jm.loc

  rabbitmq:
    image: 'enqueue/rabbitmq:latest'
    restart: 'always'
    environment:
      - VIRTUAL_HOST=rabbitmq.jm.loc
      - VIRTUAL_PORT=15672
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=jm

  mongo:
    image: 'mongo:3'
    restart: 'always'
    ports:
      - "27017:27017"
    volumes:
      - './shared:/shared'

  front:
    image: 'jwilder/nginx-proxy'
    restart: 'always'
    ports:
      - "80:80"
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
