index:
    path: /
    defaults: { _controller: 'App\Controller\FooController::fooAction' }

graph:
    path: /graph/{id}
    defaults: { _controller: 'App\Controller\FooController::graphAction' }

graph_token:
    path: /graph/token/{token}
    defaults: { _controller: 'App\Controller\FooController::graphTokenAction' }

controllers:
    resource: ../src/Controller/
    type: annotation
