# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    mongo_database: 'comrade'

    wamp_public_dsn: '%env(WAMP_PUBLIC_DSN)%'
    wamp_public_realm: '%env(WAMP_PUBLIC_REALM)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Makasim\Yadm\ChangesCollector: '@yadm.changes_collector'

    Symfony\Component\EventDispatcher\EventDispatcherInterface: '@event_dispatcher'

    Enqueue\Client\ProducerInterface:
        alias: 'enqueue.client.producer'

    Enqueue\Consumption\Extension\LoggerExtension:
        autowire: false
        arguments: ['@logger']
        tags:
            - {name: 'enqueue.consumption.extension', priority: 100 }

    App\Storage\JobStorage: '@yadm.job.storage'
    App\Storage\ExclusiveJobStorage: '@yadm.exclusive_job.storage'
    App\Storage\JobTemplateStorage: '@yadm.job_template.storage'
    App\Storage\ProcessStorage: '@yadm.process.storage'
    App\Storage\ProcessExecutionStorage: '@yadm.process_execution.storage'
    App\Infra\Error\ErrorStorage: '@yadm.error.storage'
    App\Storage\JobMetricsStorage: '@yadm.job_metrics.storage'
    App\Storage\TriggerStorage: '@yadm.trigger.storage'

    App\Infra\Error\ErrorCollector:
        tags:
            - { name: 'kernel.event_subscriber', priority: -100 }
            - { name: 'enqueue.consumption.extension', priority: -100 }

    formapro.pvm.process_execution_storage:
        autowire: false
        class: 'Formapro\Pvm\Yadm\MongoProcessStorage'
        arguments:
            - '@App\Storage\ProcessExecutionStorage'

    formapro.pvm.token_locker:
        class: 'Formapro\Pvm\Yadm\MongoTokenLocker'
        arguments:
            - '@yadm.process_execution.pessimistic_lock'

    Formapro\Pvm\ProcessStorage: '@formapro.pvm.process_execution_storage'
    Formapro\Pvm\TokenLockerInterface: '@formapro.pvm.token_locker'

    Formapro\Pvm\DefaultBehaviorRegistry: ~

    Formapro\Pvm\BehaviorRegistry: '@Formapro\Pvm\DefaultBehaviorRegistry'

    Formapro\Pvm\Enqueue\AsyncTransition: ~
    Formapro\Pvm\AsyncTransition: '@Formapro\Pvm\Enqueue\AsyncTransition'

    Formapro\Pvm\ProcessEngine:

    App\Infra\JsonSchema\LocalUriRetriver:
        autowire: false
        arguments:
            - '%kernel.root_dir%/../config/schemas'
            - 'http://comrade.forma-pro.com/schemas'

    JsonSchema\Uri\UriRetriever:
        autowire: false
        calls:
            - ['setUriRetriever', ['@App\Infra\JsonSchema\LocalUriRetriver']]

    JsonSchema\Constraints\Factory:
        autowire: false
        arguments:
            - ~
            - '@JsonSchema\Uri\UriRetriever'
            - 2 # JsonSchema\Constraints\Constraint::CHECK_MODE_TYPE_CAST

    App\Infra\JsonSchema\SchemaValidator: ~

    App\Queue\:
        resource: '../src/Queue/*'
        tags: ['enqueue.client.processor']

    App\Pvm\Behavior\:
        resource: '../src/Pvm/Behavior/*'
        tags: ['pvm.behavior']

    Formapro\Pvm\Enqueue\HandleAsyncTransitionProcessor:
        autowire: false
        arguments:
            - '@Formapro\Pvm\ProcessEngine'
            - '@formapro.pvm.process_execution_storage'
        tags: ['enqueue.client.processor']


    App\Infra\Enqueue\Producer:
        autowire: false
        arguments:
            - '@enqueue.producer'
            - '@enqueue.client.meta.queue_meta_registry'

    App\Infra\Enqueue\WaitForBrokerListener:
        autowire: false
        arguments: ['%env(ENQUEUE_DSN)%', '@logger']
        tags:
            - { name: 'kernel.event_subscriber', priority: -100 }

    App\Infra\Enqueue\LimitMessageRedeliveryExtension:
        arguments:
          - '@enqueue.transport.context'
          - 5
        tags:
            - { name: 'enqueue.consumption.extension', priority: 100 }

    App\Service\BuildMongoIndexesService:
        autowire: false
        arguments:
            - '@yadm.client'
            - '%mongo_database%'

    App\Service\ChangeJobStateService: ~

    App\Api\Controller\:
        resource: '../src/Api/Controller'
        public: true
        tags: ['controller.service_arguments']

    Quartz\Bridge\Scheduler\RemoteScheduler: '@quartz.remote.scheduler'

    App\Infra\ThruwayClient:
        arguments: ['%env(WAMP_DSN)%', '%env(WAMP_REALM)%']

    Interop\Queue\PsrContext: '@enqueue.transport.context'
